package org.opentest4j.reporting.events.java;

import org.opentest4j.reporting.events.api.Attribute;
import org.opentest4j.reporting.events.api.ChildElement;
import org.opentest4j.reporting.events.api.Context;
import org.opentest4j.reporting.events.api.QualifiedName;
import org.opentest4j.reporting.events.core.Result;

import java.io.PrintWriter;
import java.io.StringWriter;

public class Throwable extends ChildElement<Result, Throwable> {
    public static final QualifiedName ELEMENT = QualifiedName.of(JavaFactory.NAMESPACE, "throwable");
    public static final QualifiedName TYPE = QualifiedName.of(JavaFactory.NAMESPACE, "type");
    public static final QualifiedName ASSERTION_ERROR = QualifiedName.of(JavaFactory.NAMESPACE, "assertionError");

    Throwable(Context context) {
        super(context, Throwable.ELEMENT);
    }

    Throwable withThrowable(java.lang.Throwable throwable) {
        withAttribute(Attribute.of(TYPE), throwable.getClass().getName());
        withAttribute(Attribute.of(ASSERTION_ERROR), String.valueOf(throwable instanceof AssertionError));
        StringWriter stringWriter = new StringWriter();
        try (PrintWriter writer = new PrintWriter(stringWriter)) {
            throwable.printStackTrace(writer);
        }
        withCDataSection(stringWriter.toString());
        return this;
    }
}
